# Generated by Django 5.2 on 2025-04-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_womancategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='womancategories',
            old_name='categorie',
            new_name='category',
        ),
    ]
