# Generated by Django 5.2 on 2025-04-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_categorie_womancategories_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='womancategories',
            old_name='category',
            new_name='categorie',
        ),
    ]
